### ISSUE TITLE
old catalog not found

### ISSUE THREAD

**Issue by tim-moody** [worldpossible/rachel-web#4]
There used to be a catalog at http://dev.worldpossible.org/cgi/json_api_v1.pl. This has gone missing quite recently. Will it be coming back?

**Comment by JamesKainer** [comment]
It's called json_api_v2.pl now

**Comment by tim-moody** [comment]
I am aware of the v2 catalog. If the old catalog has been discontinued, would it be possible to have some of its fields added to the new catalog since both are built from the same database? Internet in a Box uses the catalog to display a list of OER2Go modules that the user can download, and fields such as description tell the user more than just the title does. Type shows the user what additional software might be required, such as kiwix. Adding back some of the old fields would be much appreciated.

Here is one entry in both the v2 and v1 catalogs for comparison:

en-afristory": {
        "logofilename": "af.png",
        "is_hidden": "No",
        "file_count": "523",
        "moddir": "en-afristory",
        "title": "African Storybook Project",
        "ksize": "182000",
        "module_id": "99",
        "lang": "en",
        "version": "v2.1"
    },

"en-afristory": {
      "age_range": "children,young adult",
      "category": "educational,entertainment",
      "description": "A collection of illustrated children's stories from many African cultures. Includes stories in English and a new graphical UI.",
      "file_count": "523",
      "index_mod_sample_url": null,
      "is_hidden": "No",
      "ksize": "182000",
      "lang": "en",
      "logo_url": null,
      "moddir": "en-afristory",
      "module_id": "99",
      "prereq_id": null,
      "prereq_note": "",
      "rating": "2.0",
      "rsync_url": "rsync://dev.worldpossible.org/rachelmods/en-afristory",
      "source_url": "http://www.africanstorybook.org/",
      "title": "African Storybook Project",
      "type": "html",
      "version": "v2.1",
      "zip_ftp_url": "ftp://dev.worldpossible.org/zipped-modules/en-afristory.zip",
      "zip_http_url": "http://dev.worldpossible.org/zipped-modules/en-afristory.zip"
    },

For Internet in a Box the most important of the previously included fields are type and description. followed by source_url. If category is still maintained it would be nice to have that too. The download fields such as rsync_url, zip_ftp_url, and zip_http_url are nice to have, but they can be calculated.

**Comment by JamesKainer** [comment]
Closed this topic by accident. The v1 file was getting spam connections, but I've added it back.

**Comment by holta** [comment]
> Closed this topic by accident. The v1 file was getting spam connections, but I've added it back.

This is fantastic news.

Huge Thanks @JamesKainer.

(If a v3 is ever necessary, please do preserve metadata wherever possible!)
